### ISSUE TITLE
Note ID ordering is alphabetical

### ISSUE THREAD

**Issue by mcrichton** [bullhorn/sdk-rest#178]
To reproduce:
```Java
BullhornData bullhornData = ... // init StandardBullhornData
Set<String> fs = new HashSet<>();
fs.add("id");
SearchParams p = ParamFactory.searchParams();
p.setSort("-noteID");
ListWrapper<Note> ns = bullhornData.search(Note.class, "*:*", fs, p);
System.out.println(ns.getData().stream().map(BullhornEntity::getId).map(Object::toString).reduce((a, b) -> a+", "+b).get());
```
Expected: `1868, 1867, 1866, ...` (highest note ID on this instance is 1868)
Actual: `999, 998, 997, ...`

It appears the results are sorted alphabetically (desc), with numbers beginning with 9 coming before larger numbers beginning with 1.

**Comment by mcrichton** [comment]
Any thoughts on this @ndickerson / @johnsully83 ? 😊

**Comment by johnsully83** [comment]
We should get in contact with BH support to open up a BH ticket.  The SDK doesn't determine how the APIs return data, so sadly we can't make a change here to fix it
