### ISSUE TITLE
sdk-rest updateEntity method for candidate returns "missing required property: userType"

### ISSUE THREAD

**Issue by SteveHiller** [bullhorn/sdk-rest#196]
To Whom It May Concern:

I am implementing a Java client of the Bullhorn Platform SDK library called sdk-rest (version 1.2.3). I am trying to update a candidate entity with the call:

`
UpdateResponse response = bhData.updateEntity(e);
`

where e is an instance of com.bullhornsdk.data.model.entity.core.standard.Candidate that I retrieved using the findEntity method.

However, I am getting the following error message:

`
com.bullhornsdk.data.exception.RestApiException: {
  "errorMessage" : "error persisting an entity of type: Candidate",
  "errors" : [ {
    "detailMessage" : "missing required property: userType",
    "propertyName" : "userType",
    "severity" : "ERROR",
    "type" : "MISSING_REQUIRED_PROPERTY"
  } ],
  "entityName" : "Candidate"
}
`

Please tell me the recommended solution for this issue.

Thanks,

Steve Hiller
Senior Analyst/Programmer

Randstad USA
2050 Spectrum Blvd
Fort Lauderdale, FL 33309
954.308.8230 (o)
Steve.Hiller@randstadusa.com......
http://www.randstad.com

**Comment by johnsully83** [comment]
Hey Steve,

Take a look at https://github.com/bullhorn/sdk-rest/issues/141.

This issue occurs when we don't pass fields to the findEntity method, which is the equivalent of asking for '*' fields from the REST API through the SDK, and then we use that same object returned by the SDK for an update.  When this happens BH truly passes back 'all' fields, including a handful that don't properly map to the Candidate entity (but are in fact fields that exist in the database on the Candidate table)...like userType.

The SDK handles these extra fields in the AbstractEntity class, where we shove all extra fields into a Map<String, Object> using the @JsonAnySetter annotation.  Similarly when we send data to the REST APIs through the SDK, this Map gets serialized back to the JSON object using a @JsonAnyGetter annotation.

The solution is to always create a new entity when you want to perform an update, as described in my the link I pasted above.  This is also best practice as far as performance goes, as it ensures the REST APIs only attempt to update the one or two fields you actually need updated.  Similarly I always recommend passing a Set<String> into any find/query/search call, as that will speed up the calls considerably (as the REST APIs will truly only pull the fields you ask for from the database)
