### ISSUE TITLE
com.bullhornsdk.data.exception.RestMappingException: 

### ISSUE THREAD

**Issue by BrianSallee** [bullhorn/sdk-rest#200]
Posting here per BHSupport

When using the following 
findEntity(com.bullhornsdk.data.model.entity.core.standard.Candidate.class, xxxxxxx)
we get 
com.bullhornsdk.data.exception.RestMappingException: 
 Error mapping jsonString to class com.bullhornsdk.data.model.entity.core.standard.Candidate. jsonString =

This is not on all candidates, but have not figured out what is different about the subset of candidates that cause this.

**Comment by johnsully83** [comment]
This looks like a change made to the REST APIs is causing an issue with the SDK.  The very first thing I'd check would be to ensure you have the latest version from Maven.  Regardless of whether we do or not, could you post the full stack trace (at least the SDK portion of it).  Also, could we post the jsonString in the error message?  It will help us identify which field/property is causing the JSON mapping error.

**Comment by BrianSallee** [comment]
John, Do you have a private email that I might submit that data through?  I don't want to paste production candidate data publicly.  If not I can change the values to be non identifying.

**Comment by BrianSallee** [comment]
John, I sent the data in question to the gmail account in your GH profile.
Much thanks
 Brian

**Comment by johnsully83** [comment]
@BrianSallee thanks for that data.  Based on that I made a fix to the SDK today which hopefully should remedy your issue (namely the companyUrl field for your configuration is marked as 'Allow multiple values' in field maps, which makes it serialize kind of strange in the REST APIs.  We've handled this for most fields but not for this specific one until now).

As of sometime tomorrow you should be able to update your SDK dependency to version 1.2.30 and you should hopefully see the issue resolved.  Currently it's still being propogated through Maven currently, but should be ready latest sometime tomorrow.

Feel free to reopen this issue or a new one if you still see issues.
