### ISSUE TITLE
MAX_TTL value?

### ISSUE THREAD

**Issue by sangaloma** [bullhorn/sdk-rest#218]
In the RestApiSession class the value of the MAX_TTL is set to 2880 minutes. I would like to know if this is the limit value of the ttl set by the BullHorn API or was it just 'randomly' (or whatever reason was) chosen by developers of this SDK?

In Other words, if I send a request directly (from postman) with the query value ttl > 2880 what will be the ttl of the returned BhRestToken?

**Comment by Allblues** [comment]
Hi. The maximum time to live of the rest session on the server-side is 2880 minutes (2 days). You will not get a longer ttl by setting a different value on your login call.

**Comment by sangaloma** [comment]
ok thanks.
