### ISSUE TITLE
Comment Field

### ISSUE THREAD

**Issue by mpaus18** [bullhorn/sdk-rest#241]
Hi,

I'm not particular familiar with APIs, but Bullhorn Support pointed me to this thread to ask my question. 

Is it possible via Bullhorn's API to pull the content out of the candidate general comments field & the contact general comments field, (restructure it if necessary) and then again via API feed this content back into a dropdown or picker field in the corresponding candidate/contact records?
If it is possible, our organisation would consider hiring a developer to do implement it.

**Comment by ndickerson** [comment]
Hi,

Yes, this certainly is possible. The Bullhorn API supports pulling content out of any field as well as inserting/updating data in any field. It sounds like the hard part will be restructuring what parts of the general comments should go into a field for a picker or dropdown. A developer could certainly do what you suggest.
