### ISSUE TITLE
customText20+ isn't available on JobOrder on SDK

### ISSUE THREAD

**Issue by SimonOkeeffe** [bullhorn/sdk-rest#348]
For a client we need customText21 and 22 on JobOrder on the SDK to pull, which they currently aren't

http://bullhorn.github.io/rest-api-docs/entityref.html#joborder

**Comment by ALNAUA** [comment]
I beleive latest sdk have those.
https://github.com/bullhorn/sdk-rest/commit/864f8dbb64e3afab1667b820b0a91bd9cb3e39cd

**Comment by SimonOkeeffe** [comment]
Can confirm
