### ISSUE TITLE
Search for JobOrders using SDK throws error when parsing address

### ISSUE THREAD

**Issue by tiredolddog** [bullhorn/sdk-rest#441]
Hey there fellas! 

I'm part of a company which uses bullhorn SDK, lately we are running into a issue when requesting the Address object from Job orders, which seems to be caused by a missing field named ‘countryCode’.

The previous version we used were 1.4.50, but it started to show issues regarding authorization and authentication through the SDK.
`com.bullhornsdk.data.api.helper.RestApiSession - Failed to get access token.`

It used to work before and even works fine when requesting through postman. Hence, we decided to update the SDK version

So currently we are running the SDK new version 2.2.2, in a grails environment version 3.1.16. We are using gradle as dependency management and listing the SDK dependency as such:
compile 'com.bullhorn:sdk-rest:2.2.2:jdk8', using the classifier :jdk8 as recommended in the README for java 8 compatibility.

The method we’re invoking which is ultimately causing the error is the BullhornData.searchForList(Class<T> type, String query, Set<String> fieldSet, SearchParams params)

When supplying the ‘address’ in the fieldSet parameter, we got the following error:

` org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V (through reference chain: com.bullhornsdk.data.model.response.list.JobOrderListWrapper["data"]->java.util.ArrayList[0]->com.bullhornsdk.data.model.entity.core.standard.JobOrder["address"]->com.bullhornsdk.data.model.entity.embedded.Address["countryCode"]); `

`nested exception is com.fasterxml.jackson.databind.JsonMappingException: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V (through reference chain: com.bullhornsdk.data.model.response.list.JobOrderListWrapper["data"]->java.util.ArrayList[0]->com.bullhornsdk.data.model.entity.core.standard.JobOrder["address"]->com.bullhornsdk.data.model.entity.embedded.Address["countryCode"])
`

We tried matching the jackson library used by the SDK (seemly 2.10.0)
Setting up a custom ObjectMapper and explicitly setting DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES as FALSE did not solved the problem either. 

Also some other options were given a chance, like using the searchForIdList and findMultipleEntity passing the ids returned from the first method. 

In this case, no error occurred, but if ‘address’ is NOT requested, a null object returns, yet we do have a result set. If  ‘address’ IS requested, though, no result set returned from findMultipleEntity method. 

I believe this is all we got so far, let me know if I can provide anymore information.

Thanks in advance!

**Comment by johnsully83** [comment]
So this does indeed look like a bug in the SDK...the 'countryCode' property of the address object isn't defined in the Address class, which is why we're seeing that error.

An easy fix would be to specify what fields inside of address you want, instead of just asking for the 'address' object.  E.g. you can pass this into your field set 'address(address1,address2,city,state,countryID)' and it should only return those properties from the Bullhorn REST API (so the extra countryCode property will not be returned from BH at all, and Jackson won't throw that Exception)

Alternatively of course feel free to open a pull request and add in the countryCode property; we can get it merged, tagged, and deployed to Maven within a day or two of a PR being opened.

**Comment by tiredolddog** [comment]
@johnsully83 thanks for the reply. We did as your suggested. By specifying the attributes like address(address1) we got it working. We have found some other problems when inserting/updating some entities, which i'm describing in a new issue.
